# Generated by Django 6.0.6 on 2026-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=25)),
                ('author_image', models.ImageField(upload_to='images/')),
                ('book_file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
