# Generated by Django 6.0.6 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adminmodel_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_branch',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
