# Generated by Django 6.0.6 on 2026-08-13 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_available_copies_issuedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(default=datetime.date(2026, 8, 27)),
        ),
    ]
