# Generated by Django 6.0.7 on 2026-09-20 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_available_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='return_date',
            field=models.DateField(default=datetime.date(2026, 10, 4)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
